<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<p class="footer-copyright">
    <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
</p>

<!-- 
<div class="col-md-5 footer-copyright">
	<p><?= $block->escapeHtml($block->getCopyright()) ?></p>
</div>
<div class="col-md-7 footer-menu">
	<nav class="navbar navbar-dark navbar-expand-md">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a class="nav-link scroll-link" href="#top-content">Top</a>
				</li>
				<li class="nav-item">
					<a class="nav-link scroll-link" href="#section-1">Section 1</a>
				</li>
				<li class="nav-item">
					<a class="nav-link scroll-link" href="#section-2">Section 2</a>
				</li>
				<li class="nav-item">
					<a class="nav-link scroll-link" href="#section-3">Section 3</a>
				</li>
				<li class="nav-item">
					<a class="nav-link scroll-link" href="#section-4">Section 4</a>
				</li>
			</ul>
		</div>
	</nav>
</div> -->
