<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<h3>Theo dõi Đa Khoa</h3>
<p>
	<a href="https://www.facebook.com/md.dakhoa.vn"><i class="fab fa-facebook"></i></a>
	<a href="https://www.facebook.com/md.dakhoa.vn"><i class="fab fa-twitter"></i></a>
	<a href="https://www.facebook.com/md.dakhoa.vn"><i class="fab fa-google-plus-g"></i></a>
	<a href="https://www.facebook.com/md.dakhoa.vn"><i class="fab fa-instagram"></i></a>
	<a href="https://www.facebook.com/md.dakhoa.vn"><i class="fab fa-pinterest"></i></a>
</p>